---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Instala pacotes que permitem que o apt seja usado sobre HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - snapd
        - python
        - git
        - vim
        - python3-docker

    - name: Criando o arquivo k3s.sh
      copy:
        src: files/k3s.sh
        dest: /root/
        owner: root
        group: root
        mode: '777'

    - name: Copiando chart 
      copy:
        src: files/super-mario/
        dest: /root/super-mario/
        owner: root
        group: root      

    - name: Instalando k3s via script 
      command: sh /root/k3s.sh

    - name: Configurando add-on de rede 
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico-typha.yaml