apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: super-mario
  name: super-mario
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: super-mario
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: super-mario
    spec:
      containers:
        - image: pengbai/docker-supermario
          name: super-mario
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
